// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

type Student struct {
	ID       int64
	Name     string
	Address  string
	City     string
	Country  string
	Pincode  string
	SatScore int64
	Passed   bool
}
