// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"database/sql"
)

type Student struct {
	ID       int64
	Name     string
	Address  sql.NullString
	City     sql.NullString
	Country  sql.NullString
	Pincode  sql.NullString
	SatScore sql.NullInt64
	Passed   interface{}
}
